using System;
using System.Collections.Generic;
using System.Text;

namespace Valley.Net.Protocols.MeterBus.EN13757_2
{
    public enum DeviceType : byte
    {
        Other = 0x00,           //Other
        Oil = 0x01,             //Oil
        Electricity = 0x02,     //Electricity
        Gas = 0x03,             //Gas
        Heat = 0x04,            //Heat (Volume measured at return temperature: outlet)
        Steam = 0x05,           //Steam
        HotWater = 0x06,        //Hot Water
        Water = 0x07,           //Water
        HCA = 0x08,             //Heat Cost Allocator.
        CompressedAir = 0x09,   //Compressed Air
        CLM = 0x0A,             //Cooling load meter (Volume measured at return temperature: outlet)
        CLM2 = 0x0B,            //Cooling load meter (Volume measured at flow temperature: inlet)
        Heat2 = 0x0C,           //Heat (Volume measured at flow temperature: inlet)
        Water2 = 0x0D,          //Heat / Cooling load meter
        HCA2 = 0x0E,            //Wärme/Kühlung
        Unknown = 0x0F,         //Unknown Medium
        Reserved_0x10 = 0x10,   //Reserved
        Reserved_0x11 = 0x11,   //Reserved
        Reserved_0x12 = 0x12,   //Reserved
        Reserved_0x13 = 0x13,   //Reserved
        CalorificValue = 0x14,  //Calorific value
        BoilingWater = 0x15,    //Boiling water
        ColdWater = 0x16,       //Cold Water
        DualWater = 0x17,       //Dual Water
        Pressure = 0x18,        //Pressure
        ADConverter = 0x19,     //A/D Converter
        SmokeDetector = 0x1A,   //Smoke detector
        RoomSensor = 0x1B,      //Room sensor
        GasDetector = 0x1C,     //Gas detector
        Reserved_0x1D = 0x1D,   //Reserved for sensors
        Reserved_0x1E = 0x1E,   //Reserved for sensors
        Reserved_0x1F = 0x1F,   //Reserved for sensors
        CircuitBreaker = 0x20,  //Circuit breaker
        Ventil = 0x21,          //Ventil
        Reserved_0x22 = 0x22,   //Reserved
        Reserved_0x23 = 0x23,   //Reserved
        Reserved_0x24 = 0x24,   //Reserved
        Display = 0x25,         //Display
        Reserved_0x26 = 0x26,   //Reserved
        Reserved_0x27 = 0x27,   //Reserved
        Sewage = 0x28,          //Sewage
        Waste = 0x29,           //Waste
        CarbonDioxide = 0x2A,   //Carbon dioxide
        Reserved_0x2B = 0x2B,   //Reserved
        Reserved_0x2C = 0x2C,   //Reserved
        Reserved_0x2D = 0x2D,   //Reserved
        Reserved_0x2E = 0x2E,   //Reserved
        Reserved_0x2F = 0x2F,   //Reserved
        Reserved_0x30 = 0x30,   //Reserved
        Reserved_0x31 = 0x31,   //Reserved
        Reserved_0x32 = 0x32,   //Reserved
        Reserved_0x33 = 0x33,   //Reserved
        Reserved_0x34 = 0x34,   //Reserved
        Reserved_0x35 = 0x35,   //Reserved
        Reserved_0x36 = 0x36,   //Reserved
        Reserved_0x37 = 0x37,   //Reserved
        Reserved_0x38 = 0x38,   //Reserved
        Reserved_0x39 = 0x39,   //Reserved
        Reserved_0x3A = 0x3A,   //Reserved
        Reserved_0x3B = 0x3B,   //Reserved
        Reserved_0x3C = 0x3C,   //Reserved
        Reserved_0x3D = 0x3D,   //Reserved
        Reserved_0x3E = 0x3E,   //Reserved
        Reserved_0x3F = 0x3F,   //Reserved
        Reserved_0x40 = 0x40,   //Reserved
        Reserved_0x41 = 0x41,   //Reserved
        Reserved_0x42 = 0x42,   //Reserved
        Reserved_0x43 = 0x43,   //Reserved
        Reserved_0x44 = 0x44,   //Reserved
        Reserved_0x45 = 0x45,   //Reserved
        Reserved_0x46 = 0x46,   //Reserved
        Reserved_0x47 = 0x47,   //Reserved
        Reserved_0x48 = 0x48,   //Reserved
        Reserved_0x49 = 0x49,   //Reserved
        Reserved_0x4A = 0x4A,   //Reserved
        Reserved_0x4B = 0x4B,   //Reserved
        Reserved_0x4C = 0x4C,   //Reserved
        Reserved_0x4D = 0x4D,   //Reserved
        Reserved_0x4E = 0x4E,   //Reserved
        Reserved_0x4F = 0x4F,   //Reserved
        Reserved_0x50 = 0x50,   //Reserved
        Reserved_0x51 = 0x51,   //Reserved
        Reserved_0x52 = 0x52,   //Reserved
        Reserved_0x53 = 0x53,   //Reserved
        Reserved_0x54 = 0x54,   //Reserved
        Reserved_0x55 = 0x55,   //Reserved
        Reserved_0x56 = 0x56,   //Reserved
        Reserved_0x57 = 0x57,   //Reserved
        Reserved_0x58 = 0x58,   //Reserved
        Reserved_0x59 = 0x59,   //Reserved
        Reserved_0x5A = 0x5A,   //Reserved
        Reserved_0x5B = 0x5B,   //Reserved
        Reserved_0x5C = 0x5C,   //Reserved
        Reserved_0x5D = 0x5D,   //Reserved
        Reserved_0x5E = 0x5E,   //Reserved
        Reserved_0x5F = 0x5F,   //Reserved
        Reserved_0x60 = 0x60,   //Reserved
        Reserved_0x61 = 0x61,   //Reserved
        Reserved_0x62 = 0x62,   //Reserved
        Reserved_0x63 = 0x63,   //Reserved
        Reserved_0x64 = 0x64,   //Reserved
        Reserved_0x65 = 0x65,   //Reserved
        Reserved_0x66 = 0x66,   //Reserved
        Reserved_0x67 = 0x67,   //Reserved
        Reserved_0x68 = 0x68,   //Reserved
        Reserved_0x69 = 0x69,   //Reserved
        Reserved_0x6A = 0x6A,   //Reserved
        Reserved_0x6B = 0x6B,   //Reserved
        Reserved_0x6C = 0x6C,   //Reserved
        Reserved_0x6D = 0x6D,   //Reserved
        Reserved_0x6E = 0x6E,   //Reserved
        Reserved_0x6F = 0x6F,   //Reserved
        Reserved_0x70 = 0x70,   //Reserved
        Reserved_0x71 = 0x71,   //Reserved
        Reserved_0x72 = 0x72,   //Reserved
        Reserved_0x73 = 0x73,   //Reserved
        Reserved_0x74 = 0x74,   //Reserved
        Reserved_0x75 = 0x75,   //Reserved
        Reserved_0x76 = 0x76,   //Reserved
        Reserved_0x77 = 0x77,   //Reserved
        Reserved_0x78 = 0x78,   //Reserved
        Reserved_0x79 = 0x79,   //Reserved
        Reserved_0x7A = 0x7A,   //Reserved
        Reserved_0x7B = 0x7B,   //Reserved
        Reserved_0x7C = 0x7C,   //Reserved
        Reserved_0x7D = 0x7D,   //Reserved
        Reserved_0x7E = 0x7E,   //Reserved
        Reserved_0x7F = 0x7F,   //Reserved
        Reserved_0x80 = 0x80,   //Reserved
        Reserved_0x81 = 0x81,   //Reserved
        Reserved_0x82 = 0x82,   //Reserved
        Reserved_0x83 = 0x83,   //Reserved
        Reserved_0x84 = 0x84,   //Reserved
        Reserved_0x85 = 0x85,   //Reserved
        Reserved_0x86 = 0x86,   //Reserved
        Reserved_0x87 = 0x87,   //Reserved
        Reserved_0x88 = 0x88,   //Reserved
        Reserved_0x89 = 0x89,   //Reserved
        Reserved_0x8A = 0x8A,   //Reserved
        Reserved_0x8B = 0x8B,   //Reserved
        Reserved_0x8C = 0x8C,   //Reserved
        Reserved_0x8D = 0x8D,   //Reserved
        Reserved_0x8E = 0x8E,   //Reserved
        Reserved_0x8F = 0x8F,   //Reserved
        Reserved_0x90 = 0x90,   //Reserved
        Reserved_0x91 = 0x91,   //Reserved
        Reserved_0x92 = 0x92,   //Reserved
        Reserved_0x93 = 0x93,   //Reserved
        Reserved_0x94 = 0x94,   //Reserved
        Reserved_0x95 = 0x95,   //Reserved
        Reserved_0x96 = 0x96,   //Reserved
        Reserved_0x97 = 0x97,   //Reserved
        Reserved_0x98 = 0x98,   //Reserved
        Reserved_0x99 = 0x99,   //Reserved
        Reserved_0x9A = 0x9A,   //Reserved
        Reserved_0x9B = 0x9B,   //Reserved
        Reserved_0x9C = 0x9C,   //Reserved
        Reserved_0x9D = 0x9D,   //Reserved
        Reserved_0x9E = 0x9E,   //Reserved
        Reserved_0x9F = 0x9F,   //Reserved
        Reserved_0xA0 = 0xA0,   //Reserved
        Reserved_0xA1 = 0xA1,   //Reserved
        Reserved_0xA2 = 0xA2,   //Reserved
        Reserved_0xA3 = 0xA3,   //Reserved
        Reserved_0xA4 = 0xA4,   //Reserved
        Reserved_0xA5 = 0xA5,   //Reserved
        Reserved_0xA6 = 0xA6,   //Reserved
        Reserved_0xA7 = 0xA7,   //Reserved
        Reserved_0xA8 = 0xA8,   //Reserved
        Reserved_0xA9 = 0xA9,   //Reserved
        Reserved_0xAA = 0xAA,   //Reserved
        Reserved_0xAB = 0xAB,   //Reserved
        Reserved_0xAC = 0xAC,   //Reserved
        Reserved_0xAD = 0xAD,   //Reserved
        Reserved_0xAE = 0xAE,   //Reserved
        Reserved_0xAF = 0xAF,   //Reserved
        Reserved_0xB0 = 0xB0,   //Reserved
        Reserved_0xB1 = 0xB1,   //Reserved
        Reserved_0xB2 = 0xB2,   //Reserved
        Reserved_0xB3 = 0xB3,   //Reserved
        Reserved_0xB4 = 0xB4,   //Reserved
        Reserved_0xB5 = 0xB5,   //Reserved
        Reserved_0xB6 = 0xB6,   //Reserved
        Reserved_0xB7 = 0xB7,   //Reserved
        Reserved_0xB8 = 0xB8,   //Reserved
        Reserved_0xB9 = 0xB9,   //Reserved
        Reserved_0xBA = 0xBA,   //Reserved
        Reserved_0xBB = 0xBB,   //Reserved
        Reserved_0xBC = 0xBC,   //Reserved
        Reserved_0xBD = 0xBD,   //Reserved
        Reserved_0xBE = 0xBE,   //Reserved
        Reserved_0xBF = 0xBF,   //Reserved
        Reserved_0xC0 = 0xC0,   //Reserved
        Reserved_0xC1 = 0xC1,   //Reserved
        Reserved_0xC2 = 0xC2,   //Reserved
        Reserved_0xC3 = 0xC3,   //Reserved
        Reserved_0xC4 = 0xC4,   //Reserved
        Reserved_0xC5 = 0xC5,   //Reserved
        Reserved_0xC6 = 0xC6,   //Reserved
        Reserved_0xC7 = 0xC7,   //Reserved
        Reserved_0xC8 = 0xC8,   //Reserved
        Reserved_0xC9 = 0xC9,   //Reserved
        Reserved_0xCA = 0xCA,   //Reserved
        Reserved_0xCB = 0xCB,   //Reserved
        Reserved_0xCC = 0xCC,   //Reserved
        Reserved_0xCD = 0xCD,   //Reserved
        Reserved_0xCE = 0xCE,   //Reserved
        Reserved_0xCF = 0xCF,   //Reserved
        Reserved_0xD0 = 0xD0,   //Reserved
        Reserved_0xD1 = 0xD1,   //Reserved
        Reserved_0xD2 = 0xD2,   //Reserved
        Reserved_0xD3 = 0xD3,   //Reserved
        Reserved_0xD4 = 0xD4,   //Reserved
        Reserved_0xD5 = 0xD5,   //Reserved
        Reserved_0xD6 = 0xD6,   //Reserved
        Reserved_0xD7 = 0xD7,   //Reserved
        Reserved_0xD8 = 0xD8,   //Reserved
        Reserved_0xD9 = 0xD9,   //Reserved
        Reserved_0xDA = 0xDA,   //Reserved
        Reserved_0xDB = 0xDB,   //Reserved
        Reserved_0xDC = 0xDC,   //Reserved
        Reserved_0xDD = 0xDD,   //Reserved
        Reserved_0xDE = 0xDE,   //Reserved
        Reserved_0xDF = 0xDF,   //Reserved
        Reserved_0xE0 = 0xE0,   //Reserved
        Reserved_0xE1 = 0xE1,   //Reserved
        Reserved_0xE2 = 0xE2,   //Reserved
        Reserved_0xE3 = 0xE3,   //Reserved
        Reserved_0xE4 = 0xE4,   //Reserved
        Reserved_0xE5 = 0xE5,   //Reserved
        Reserved_0xE6 = 0xE6,   //Reserved
        Reserved_0xE7 = 0xE7,   //Reserved
        Reserved_0xE8 = 0xE8,   //Reserved
        Reserved_0xE9 = 0xE9,   //Reserved
        Reserved_0xEA = 0xEA,   //Reserved
        Reserved_0xEB = 0xEB,   //Reserved
        Reserved_0xEC = 0xEC,   //Reserved
        Reserved_0xED = 0xED,   //Reserved
        Reserved_0xEE = 0xEE,   //Reserved
        Reserved_0xEF = 0xEF,   //Reserved
        Reserved_0xF0 = 0xF0,   //Reserved
        Reserved_0xF1 = 0xF1,   //Reserved
        Reserved_0xF2 = 0xF2,   //Reserved
        Reserved_0xF3 = 0xF3,   //Reserved
        Reserved_0xF4 = 0xF4,   //Reserved
        Reserved_0xF5 = 0xF5,   //Reserved
        Reserved_0xF6 = 0xF6,   //Reserved
        Reserved_0xF7 = 0xF7,   //Reserved
        Reserved_0xF8 = 0xF8,   //Reserved
        Reserved_0xF9 = 0xF9,   //Reserved
        Reserved_0xFA = 0xFA,   //Reserved
        Reserved_0xFB = 0xFB,   //Reserved
        Reserved_0xFC = 0xFC,   //Reserved
        Reserved_0xFD = 0xFD,   //Reserved
        Reserved_0xFE = 0xFE,   //Reserved
        Reserved_0xFF = 0xFF,   //Reserved

    }
}
