<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Serial port transport for the Valley M-Bus protocol library</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Valley.Net.Protocols.MeterBus.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Valley.Net.Protocols.MeterBus.Abstractions\Valley.Net.Protocols.MeterBus.Abstractions.csproj" />
  </ItemGroup>

</Project>
